version: '2'
services:
  nginx-proxy:
    image: tpurplepeopleeater/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
     tmpfs:
      - /tmp

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

